apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  redis.conf: |
    maxmemory {{ .Values.config.maxmemory }}
    maxmemory-policy {{ .Values.config.maxmemoryPolicy }}
