apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-clusters
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yaronyadid/argocd-example.git
    targetRevision: HEAD
    directory:
      include: "clusters/*/applicationset.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
