apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster2-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yaronyadid/argocd-example.git
    targetRevision: HEAD
    path: apps
    helm:
      valueFiles:
        - ../../common/values.yaml
        - ../../clusters/cluster2/values.yaml
  destination:
    server: https://kubernetes.cluster2.example.com
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
