# Common values for all clusters
global:
  imageRegistry: docker.io
  imagePullSecrets: []

# Default values that can be overridden by cluster-specific configs
nginx:
  service:
    type: ClusterIP
    port: 80

redis:
  service:
    type: ClusterIP
    port: 6379
