# Default values for apps umbrella chart
global:
  environment: production

nginx:
  enabled: true
  replicaCount: 1
  image:
    repository: nginx
    tag: 1.21.6
  service:
    type: ClusterIP
    port: 80

redis:
  enabled: true
  replicaCount: 1
  image:
    repository: redis
    tag: 6.2.6
  service:
    type: ClusterIP
    port: 6379
